apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: common-latest
placementBindingDefaults:
  name: common-placement-binding
policyDefaults:
  # categories: []
  #controls:
  #  - PR.DS-1 Data-at-rest
  namespace: ztp-common
  # Use an existing placement rule so that placement bindings can be consolidated
  placement:
    labelSelector:
      common: "true"
      #      du-profile: "latest"
  remediationAction: enforce
  severity: low
  # standards: []
  namespaceSelector:
    exclude:
      - kube-*
    include:
      - '*'
  evaluationInterval:
    compliant: 10m
    noncompliant: 10s
policies:
- name: common-subscriptions-policy-latest
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "2"
  manifests:
    # SRIOV operator
    - path: source-crs/SriovSubscriptionNS.yaml
    - path: source-crs/SriovSubscriptionOperGroup.yaml
    - path: source-crs/SriovSubscription.yaml
    - path: source-crs/SriovOperatorStatus.yaml
    # Storage operator
    - path: source-crs/StorageNS.yaml
    - path: source-crs/StorageOperGroup.yaml
    - path: source-crs/StorageSubscription.yaml
    - path: source-crs/StorageOperatorStatus.yaml
