---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "common-latest"
  namespace: "ztp-common"
spec:
  bindingRules:
    # These policies will correspond to all clusters with this label:
    common: "true"
    #  du-profile: "latest"
  sourceFiles:
    # Create operators policies that will be installed in all clusters
    - fileName: SriovSubscriptionNS.yaml
      policyName: "subscriptions-policy"
    - fileName: SriovSubscriptionOperGroup.yaml
      policyName: "subscriptions-policy"
    - fileName: SriovSubscription.yaml
      policyName: "subscriptions-policy"
    - fileName: SriovOperatorStatus.yaml
      policyName: "subscriptions-policy"
      #    - fileName: PtpSubscriptionNS.yaml
      #policyName: "subscriptions-policy"
      # - fileName: PtpSubscriptionOperGroup.yaml
      #policyName: "subscriptions-policy"
      #- fileName: PtpSubscription.yaml
      #policyName: "subscriptions-policy"
      # - fileName: PtpOperatorStatus.yaml
      #policyName: "subscriptions-policy"
      #- fileName: ClusterLogNS.yaml
      #policyName: "subscriptions-policy"
      #- fileName: ClusterLogOperGroup.yaml
      #policyName: "subscriptions-policy"
      #- fileName: ClusterLogSubscription.yaml
      #policyName: "subscriptions-policy"
      #- fileName: ClusterLogOperatorStatus.yaml
      #policyName: "subscriptions-policy"
    - fileName: StorageNS.yaml
      policyName: "subscriptions-policy"
    - fileName: StorageOperGroup.yaml
      policyName: "subscriptions-policy"
    - fileName: StorageSubscription.yaml
      policyName: "subscriptions-policy"
    - fileName: StorageOperatorStatus.yaml
      policyName: "subscriptions-policy"
    - fileName: DefaultCatsrc.yaml
      policyName: "config-policy"
      # The Subscriptions all point to redhat-operators. The OperatorHub CR
      # disables the defaults and this CR replaces redhat-operators with a
      # CatalogSource pointing to the disconnected registry. Including both of
      # these in the same policy orders their application to the cluster.
      metadata:
        name: redhat-operators-disconnected
      spec:
        displayName: redhat-operators-disconnected
        image: registry.acm.example.com:5000/redhat/redhat-operator-index:v4.12
    # - fileName: AmqSubscriptionNS.yaml
    #   policyName: "subscriptions-policy"
    # - fileName: AmqSubscriptionOperGroup.yaml
    #   policyName: "subscriptions-policy"
    # - fileName: AmqSubscription.yaml
    #   policyName: "subscriptions-policy"
    # - fileName: BareMetalEventRelaySubscriptionNS.yaml
    #   policyName: "subscriptions-policy"
    # - fileName: BareMetalEventRelaySubscriptionOperGroup.yaml
    #   policyName: "subscriptions-policy"
    # - fileName: BareMetalEventRelaySubscription.yaml
    #   policyName: "subscriptions-policy"
    #- fileName: ReduceMonitoringFootprint.yaml
    #  policyName: "config-policy"
    #
    # These CRs are in support of installation from a disconnected registry
    #
